### PR TITLE
chore: try to fix ci issue

### PR DESCRIPTION
**Pull request by Uzlopak**

### CODE REVIEW

**Comment by Fdawgs** [comment]
As it's Windows Node 22 I assume it's related to https://github.com/fastify/fastify/pull/5889?

**Comment by Uzlopak** [comment]
it seems that we are using 22.11.0 in the ci for win.

**Comment by Uzlopak** [comment]
@Fdawgs 

This seems to fix it. PTAL

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
