### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by nileshmali**
As titled

### CODE REVIEW

**Comment by allevo** [comment]
test failing

**Comment by nileshmali** [comment]
Seem like some other issue as test are passing on my local with same node version

**Comment by mcollina** [comment]
restarted ci
Il giorno ven 7 set 2018 alle 08:50 Nilesh Namdeo Mali <
notifications@github.com> ha scritto:

**Comment by nileshmali** [comment]
Thanks. CI would be green once #26 lands on master.

**Comment by nileshmali** [comment]
@mcollina Seems like builds are intermittently failing on Node 10.10.0

**Comment by mcollina** [comment]
I concur, would you like to send a PR?

**Pull request merged**
