### PR TITLE
Added request args to rewriteHeaders

### PR DESCRIPTION
**Pull request by AlisaLC**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by AlisaLC** [comment]
closes #223

**Comment by Eomm** [comment]
Could you add some test and update the README?

**Comment by AlisaLC** [comment]
Docs were already updated. Tests are now updated to contain req in rewriteHeader. `req` is used as second argument and is optional so it won't cause conflict with already existing codes.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
