### PR TITLE
improve test coverage

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — COMMENTED** [review]
Could you update the .taprc as well?

**Comment by Uzlopak** [comment]
Done. For 100% coverage we would need to test this line
https://github.com/fastify/fastify-reply-from/blob/d4949f4a9697d84186191000f4a5859d5ae3fecd/lib/request.js#L225

I have no clue how this can be tested.

**Comment by Uzlopak** [comment]
Strange. Seems like in older node the coverage is not given? Is it because node14 has no http2 support or so?

**Comment by Eomm** [comment]
There are some bypass:

https://github.com/fastify/fastify-reply-from/blob/eb049b1c22b8372225d22e5056020ece7db43886/test/unix-http-undici-from.js#L11

I would be ok to lower the values for now, we can open an issue on fastify-workflow to manage these use cases

**Comment by Uzlopak** [comment]
Lowered the threshold

**Pull request merged**
