### PR TITLE
perf: replace querystring with fast-querystring

### PR DESCRIPTION
**Pull request by anonrig**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Fdawgs — CHANGES_REQUESTED** [review]
I think we should wait until this is at a stable version (v1.x) before doing this. From the rapid progress @anonrig is making I don't think that's far off!

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you please add an option to configure the querystring module to use? Like in Fastify.

**Comment by anonrig** [comment]
Fastify was using `querystringParser` and this package is using stringifier. I thought of `querystringStringifier` but I'm open to suggestions @Fdawgs & @mcollina

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Comment by anonrig** [comment]
I removed the last commit, this is actually implemented already @mcollina https://github.com/fastify/fastify-reply-from#querystring-or-querystringsearch-requrl

**Review by mcollina — APPROVED** [review]
lgtm did you check how much this improved perf (if at all)?

**Comment by anonrig** [comment]
@mcollina I didn't do a benchmark, but `fast-querystring`.stringify is 20% faster than `querystring`

**Comment by Uzlopak** [comment]
Can we decorate fastify with querystring and the plugins consume that instead of clustering the option everywhere?

**Comment by anonrig** [comment]
@Fdawgs  I released 1.0. I think it is stable enough.

**Review by Fdawgs — APPROVED** [review]

**Comment by Eomm** [comment]
Do we agree to release it as a minor version?

**Comment by anonrig** [comment]
It is a non-breaking change, if we are following sem-ver.

**Pull request merged**
