### PR TITLE
types: add `contentTypesToEncode` option

### PR DESCRIPTION
**Pull request by mircoc**
Added contentTypesToEncode option definition for typescript

### CODE REVIEW

**Review by darkgl0w — COMMENTED** [review]
Can you add a unit test for this change inside the `test/index.test-d.ts` file please ?

**Comment by mircoc** [comment]
I didn't find how to run test for typescript, anyway I added the option in the existing test file for typescript with all options.

**Comment by darkgl0w** [comment]
> I didn't find how to run test for typescript, anyway I added the option in the existing test file for typescript with all options.

@mircoc > you need to run the `typescript` npm script with the `npm run typescript` command in your local environment :)

**Review by darkgl0w — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]

**Pull request merged**
